name: 'Integration'

on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - 'main'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  public:
    if: ${{ github.event_name == 'push' || github.repository == github.event.pull_request.head.repo.full_name && github.actor != 'dependabot[bot]' }}
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v3'

    - uses: 'actions/setup-node@v3'
      with:
        node-version: '16.x'

    - name: 'npm build'
      run: 'npm ci && npm run build'

    - uses: 'google-github-actions/auth@main'
      with:
        workload_identity_provider: '${{ secrets.WIF_PROVIDER_NAME }}'
        service_account: '${{ secrets.SERVICE_ACCOUNT_EMAIL }}'

    - name: 'get-gke-credentials'
      uses: './'
      with:
        project_id: '${{ secrets.PROJECT_ID }}'
        cluster_name: '${{ secrets.PUBLIC_CLUSTER_NAME }}'
        location: '${{ secrets.PUBLIC_CLUSTER_LOCATION }}'

    - name: 'kubectl'
      run: |-
        kubectl get ns

  private:
    if: ${{ github.event_name == 'push' || github.repository == github.event.pull_request.head.repo.full_name && github.actor != 'dependabot[bot]' }}
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v3'

    - uses: 'actions/setup-node@v3'
      with:
        node-version: '16.x'

    - name: 'npm build'
      run: 'npm ci && npm run build'

    - uses: 'google-github-actions/auth@main'
      with:
        workload_identity_provider: '${{ secrets.WIF_PROVIDER_NAME }}'
        service_account: '${{ secrets.SERVICE_ACCOUNT_EMAIL }}'

    - name: 'get-gke-credentials'
      uses: './'
      with:
        project_id: '${{ secrets.PROJECT_ID }}'
        cluster_name: '${{ secrets.PRIVATE_CLUSTER_NAME }}'
        location: '${{ secrets.PRIVATE_CLUSTER_LOCATION }}'
        use_connect_gateway: 'true'

    - name: 'kubectl'
      run: |-
        kubectl get ns
