name: 'Unit'

on:
  push:
    branches:
      - 'main'
      - 'release/**/*'
  pull_request:
    branches:
      - 'main'
      - 'release/**/*'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  unit:
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu-latest'
          - 'windows-latest'
          - 'macos-latest'
    runs-on: '${{ matrix.os }}'

    steps:
      - uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # ratchet:actions/checkout@v4

      - uses: 'actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a' # ratchet:actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - name: 'npm build'
        run: 'npm ci && npm run build'

      - uses: 'google-github-actions/auth@v2' # ratchet:exclude
        with:
          workload_identity_provider: '${{ vars.WIF_PROVIDER_NAME }}'
          service_account: '${{ vars.SERVICE_ACCOUNT_EMAIL }}'

      - name: 'npm test'
        env:
          TEST_PROJECT_ID: '${{ vars.PROJECT_ID }}'
          TEST_CLUSTER_NAME: '${{ vars.PUBLIC_CLUSTER_NAME }}'
          TEST_CLUSTER_LOCATION: '${{ vars.PUBLIC_CLUSTER_LOCATION }}'
        run: 'npm run test'
